server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: konnect-search-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

com:
  kong:
    konnect:
      search:
        cdc:
          file-path: stream.jsonl
        kafka:
          topic-name: konnect-cdc-events
          replication-factor: 1
          partitions: 1
          consumer-group-id: konnect-search-group
          boostrap-servers: localhost:9092
        open-search:
          host: localhost
          port: 9200
          scheme: http
          index: cdc
resilience4j:
  circuitbreaker:
    instances:
      kafkaCircuitBreaker:
        failureRateThreshold: 50
        waitDurationInOpenState: 60s
        ringBufferSizeInHalfOpenState: 10
        ringBufferSizeInClosedState: 100
      openSearchCircuitBreaker:
        failureRateThreshold: 50
        waitDurationInOpenState: 60s
        ringBufferSizeInHalfOpenState: 10
        ringBufferSizeInClosedState: 100
  retry:
    instances:
      kafkaRetry:
        maxAttempts: 5
        waitDuration: 500ms
      openSearchRetry:
        maxAttempts: 5
        waitDuration: 500ms